[project]
name = "grabhackathon"
version = "0.1.0"
description = "Grab Hackathon submission by Chai and Biscuit"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-core>=0.3.75",
    "langchain-google-genai>=2.1.10",
    "python-dotenv>=1.1.1",
    "streamlit>=1.49.1",
]
